const defaultCategories = [
  {
    name: 'Starters',
    order: 1,
    items: [
      // 🥗 VEG STARTERS
      { name: 'Gobi 65', price: 190, vegType: 'veg', subCategory: '🥗 VEG STARTERS' },
      { name: 'Gobi Manchurian', price: 190, vegType: 'veg', subCategory: '🥗 VEG STARTERS' },
      { name: 'Chilli Gobi', price: 190, vegType: 'veg', subCategory: '🥗 VEG STARTERS' },
      { name: 'Paneer 65', price: 240, vegType: 'veg', subCategory: '🥗 VEG STARTERS' },
      { name: 'Chilli Paneer', price: 240, vegType: 'veg', isBestseller: true, subCategory: '🥗 VEG STARTERS' },
      { name: 'Paneer Manchurian', price: 240, vegType: 'veg', subCategory: '🥗 VEG STARTERS' },
      { name: 'Paneer Majestic', price: 260, vegType: 'veg', isBestseller: true, subCategory: '🥗 VEG STARTERS' },
      { name: 'Paneer Tikka', price: 260, vegType: 'veg', subCategory: '🥗 VEG STARTERS' },
      { name: 'Crispy Corn', price: 210, vegType: 'veg', isBestseller: true, subCategory: '🥗 VEG STARTERS' },
      { name: 'Corn Fry', price: 190, vegType: 'veg', subCategory: '🥗 VEG STARTERS' },
      { name: 'Baby Corn 65', price: 210, vegType: 'veg', subCategory: '🥗 VEG STARTERS' },
      { name: 'Baby Corn Manchurian', price: 210, vegType: 'veg', subCategory: '🥗 VEG STARTERS' },
      { name: 'Chilli Baby Corn', price: 210, vegType: 'veg', subCategory: '🥗 VEG STARTERS' },
      { name: 'Crispy Baby Corn', price: 220, vegType: 'veg', subCategory: '🥗 VEG STARTERS' },
      { name: 'Mushroom 65', price: 230, vegType: 'veg', subCategory: '🥗 VEG STARTERS' },
      { name: 'Mushroom Manchurian', price: 230, vegType: 'veg', subCategory: '🥗 VEG STARTERS' },
      { name: 'Chilli Mushroom', price: 230, vegType: 'veg', subCategory: '🥗 VEG STARTERS' },
      { name: 'Pepper Mushroom', price: 240, vegType: 'veg', subCategory: '🥗 VEG STARTERS' },
      { name: 'Mushroom Fry', price: 230, vegType: 'veg', subCategory: '🥗 VEG STARTERS' },
      { name: 'Veg Manchurian', price: 180, vegType: 'veg', isBestseller: true, subCategory: '🥗 VEG STARTERS' },
      { name: 'Crispy Veg', price: 190, vegType: 'veg', subCategory: '🥗 VEG STARTERS' },
      { name: 'Veg 65', price: 180, vegType: 'veg', subCategory: '🥗 VEG STARTERS' },
      { name: 'Veg Spring Rolls', price: 200, vegType: 'veg', subCategory: '🥗 VEG STARTERS' },
      { name: 'Hara Bhara Kebab', price: 220, vegType: 'veg', subCategory: '🥗 VEG STARTERS' },
      { name: 'Veg Seekh Kebab', price: 220, vegType: 'veg', subCategory: '🥗 VEG STARTERS' },
      { name: 'Kaju Pakoda', price: 240, vegType: 'veg', subCategory: '🥗 VEG STARTERS' },
      { name: 'Masala Papad', price: 80, vegType: 'veg', subCategory: '🥗 VEG STARTERS' },
      { name: 'French Fries', price: 140, vegType: 'veg', subCategory: '🥗 VEG STARTERS' },

      // 🍗 NON VEG STARTERS
      { name: 'Chicken 65', price: 280, vegType: 'non-veg', isBestseller: true, subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Chilli Chicken', price: 280, vegType: 'non-veg', isBestseller: true, subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Chicken Manchurian', price: 280, vegType: 'non-veg', subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Chicken Majestic', price: 290, vegType: 'non-veg', isBestseller: true, subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Chicken 555', price: 290, vegType: 'non-veg', subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Chicken 999', price: 290, vegType: 'non-veg', subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Chicken Lollipop', price: 310, vegType: 'non-veg', isBestseller: true, subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Chicken Drumsticks', price: 310, vegType: 'non-veg', subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Chicken Wings', price: 290, vegType: 'non-veg', subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Chicken Pakoda', price: 260, vegType: 'non-veg', subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Chicken Fry', price: 270, vegType: 'non-veg', subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Kodi Vepudu', price: 310, vegType: 'non-veg', isBestseller: true, subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Kodi Miriyala Vepudu', price: 320, vegType: 'non-veg', spicyLevel: 2, subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Guntur Chilli Chicken', price: 290, vegType: 'non-veg', spicyLevel: 3, subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Pepper Chicken', price: 290, vegType: 'non-veg', spicyLevel: 2, subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Ginger Chicken', price: 280, vegType: 'non-veg', subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Garlic Chicken', price: 280, vegType: 'non-veg', subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Lemon Chicken', price: 280, vegType: 'non-veg', subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Dragon Chicken', price: 310, vegType: 'non-veg', spicyLevel: 2, subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Schezwan Chicken', price: 290, vegType: 'non-veg', spicyLevel: 2, subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Crispy Chicken', price: 290, vegType: 'non-veg', subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Chicken Roast', price: 320, vegType: 'non-veg', subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Rayalaseema Chicken Fry', price: 320, vegType: 'non-veg', spicyLevel: 3, subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Konaseema Chicken Fry', price: 320, vegType: 'non-veg', spicyLevel: 2, subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Telangana Kodi Vepudu', price: 320, vegType: 'non-veg', spicyLevel: 2, subCategory: '🍗 NON VEG STARTERS' },
      { name: 'Karimnagar Chicken Wings', price: 310, vegType: 'non-veg', spicyLevel: 2, subCategory: '🍗 NON VEG STARTERS' },

      // 🔥 TANDOORI / KEBAB STARTERS
      { name: 'Tandoori Chicken', price: 360, vegType: 'non-veg', isBestseller: true, subCategory: '🔥 TANDOORI / KEBAB STARTERS' },
      { name: 'Chicken Tikka', price: 320, vegType: 'non-veg', isBestseller: true, subCategory: '🔥 TANDOORI / KEBAB STARTERS' },
      { name: 'Chicken Malai Tikka', price: 340, vegType: 'non-veg', subCategory: '🔥 TANDOORI / KEBAB STARTERS' },
      { name: 'Chicken Tangdi Kebab', price: 340, vegType: 'non-veg', subCategory: '🔥 TANDOORI / KEBAB STARTERS' },
      { name: 'Chicken Seekh Kebab', price: 330, vegType: 'non-veg', subCategory: '🔥 TANDOORI / KEBAB STARTERS' },
      { name: 'Chicken Reshmi Kebab', price: 340, vegType: 'non-veg', subCategory: '🔥 TANDOORI / KEBAB STARTERS' },
      { name: 'Chicken Hariyali Kebab', price: 330, vegType: 'non-veg', subCategory: '🔥 TANDOORI / KEBAB STARTERS' },
      { name: 'Chicken Achari Kebab', price: 330, vegType: 'non-veg', subCategory: '🔥 TANDOORI / KEBAB STARTERS' },
      { name: 'Chicken Garlic Kebab', price: 330, vegType: 'non-veg', subCategory: '🔥 TANDOORI / KEBAB STARTERS' },
      { name: 'Murgh Malai Kebab', price: 350, vegType: 'non-veg', subCategory: '🔥 TANDOORI / KEBAB STARTERS' },
      { name: 'Paneer Tikka', price: 270, vegType: 'veg', subCategory: '🔥 TANDOORI / KEBAB STARTERS' },
      { name: 'Paneer Malai Tikka', price: 280, vegType: 'veg', subCategory: '🔥 TANDOORI / KEBAB STARTERS' },
      { name: 'Paneer Achari Tikka', price: 270, vegType: 'veg', subCategory: '🔥 TANDOORI / KEBAB STARTERS' },
      { name: 'Paneer Hariyali Tikka', price: 270, vegType: 'veg', subCategory: '🔥 TANDOORI / KEBAB STARTERS' },
      { name: 'Hara Bhara Kebab', price: 230, vegType: 'veg', subCategory: '🔥 TANDOORI / KEBAB STARTERS' },
      { name: 'Veg Seekh Kebab', price: 230, vegType: 'veg', subCategory: '🔥 TANDOORI / KEBAB STARTERS' },

      // 🐟 FISH STARTERS
      { name: 'Apollo Fish', price: 340, vegType: 'non-veg', isBestseller: true, subCategory: '🐟 FISH STARTERS' },
      { name: 'Fish 65', price: 330, vegType: 'non-veg', subCategory: '🐟 FISH STARTERS' },
      { name: 'Fish Fry', price: 330, vegType: 'non-veg', isBestseller: true, subCategory: '🐟 FISH STARTERS' },
      { name: 'Andhra Fish Fry', price: 340, vegType: 'non-veg', spicyLevel: 2, subCategory: '🐟 FISH STARTERS' },
      { name: 'Chepa Vepudu', price: 350, vegType: 'non-veg', isBestseller: true, spicyLevel: 2, subCategory: '🐟 FISH STARTERS' },
      { name: 'Chilli Fish', price: 330, vegType: 'non-veg', subCategory: '🐟 FISH STARTERS' },
      { name: 'Fish Manchurian', price: 330, vegType: 'non-veg', subCategory: '🐟 FISH STARTERS' },
      { name: 'Ginger Fish', price: 330, vegType: 'non-veg', subCategory: '🐟 FISH STARTERS' },
      { name: 'Pepper Fish', price: 340, vegType: 'non-veg', spicyLevel: 2, subCategory: '🐟 FISH STARTERS' },
      { name: 'Schezwan Fish', price: 340, vegType: 'non-veg', spicyLevel: 2, subCategory: '🐟 FISH STARTERS' },
      { name: 'Fish Fingers', price: 320, vegType: 'non-veg', subCategory: '🐟 FISH STARTERS' },
      { name: 'Fish Tikka', price: 350, vegType: 'non-veg', subCategory: '🐟 FISH STARTERS' },
      { name: 'Fish Roast', price: 350, vegType: 'non-veg', subCategory: '🐟 FISH STARTERS' },
      { name: 'Salt & Pepper Fish', price: 340, vegType: 'non-veg', subCategory: '🐟 FISH STARTERS' },

      // 🦐 PRAWN STARTERS
      { name: 'Prawns 65', price: 360, vegType: 'non-veg', subCategory: '🦐 PRAWN STARTERS' },
      { name: 'Prawns Fry', price: 370, vegType: 'non-veg', isBestseller: true, subCategory: '🦐 PRAWN STARTERS' },
      { name: 'Royyala Vepudu', price: 380, vegType: 'non-veg', isBestseller: true, spicyLevel: 2, subCategory: '🦐 PRAWN STARTERS' },
      { name: 'Chilli Prawns', price: 360, vegType: 'non-veg', subCategory: '🦐 PRAWN STARTERS' },
      { name: 'Loose Prawns', price: 380, vegType: 'non-veg', isBestseller: true, subCategory: '🦐 PRAWN STARTERS' },
      { name: 'Pepper Prawns', price: 370, vegType: 'non-veg', spicyLevel: 2, subCategory: '🦐 PRAWN STARTERS' },
      { name: 'Garlic Prawns', price: 360, vegType: 'non-veg', subCategory: '🦐 PRAWN STARTERS' },
      { name: 'Butter Garlic Prawns', price: 390, vegType: 'non-veg', isChefSpecial: true, subCategory: '🦐 PRAWN STARTERS' },
      { name: 'Golden Fried Prawns', price: 380, vegType: 'non-veg', subCategory: '🦐 PRAWN STARTERS' },
      { name: 'Achari Prawns', price: 370, vegType: 'non-veg', subCategory: '🦐 PRAWN STARTERS' },
      { name: 'Hariyali Prawns', price: 370, vegType: 'non-veg', subCategory: '🦐 PRAWN STARTERS' },
    ],
  },
  {
    name: 'Biryanis',
    order: 2,
    items: [
      // 🥦 VEG BIRYANI
      { name: 'Veg Biryani', price: 240, vegType: 'veg', subCategory: '🥦 VEG BIRYANI' },
      { name: 'Vegetable Dum Biryani', price: 260, vegType: 'veg', subCategory: '🥦 VEG BIRYANI' },
      { name: 'Veg Dum Biryani', price: 260, vegType: 'veg', subCategory: '🥦 VEG BIRYANI' },
      { name: 'Paneer Biryani', price: 290, vegType: 'veg', isBestseller: true, subCategory: '🥦 VEG BIRYANI' },
      { name: 'Paneer Tikka Biryani', price: 310, vegType: 'veg', subCategory: '🥦 VEG BIRYANI' },
      { name: 'Mushroom Biryani', price: 290, vegType: 'veg', subCategory: '🥦 VEG BIRYANI' },
      { name: 'Mushroom Dum Biryani', price: 300, vegType: 'veg', subCategory: '🥦 VEG BIRYANI' },
      { name: 'Baby Corn Biryani', price: 280, vegType: 'veg', subCategory: '🥦 VEG BIRYANI' },
      { name: 'Kaju Biryani', price: 320, vegType: 'veg', isBestseller: true, subCategory: '🥦 VEG BIRYANI' },
      { name: 'Kaju Paneer Biryani', price: 340, vegType: 'veg', subCategory: '🥦 VEG BIRYANI' },
      { name: 'Corn Biryani', price: 260, vegType: 'veg', subCategory: '🥦 VEG BIRYANI' },
      { name: 'Mix Veg Biryani', price: 270, vegType: 'veg', subCategory: '🥦 VEG BIRYANI' },
      { name: 'Jackfruit Biryani', price: 290, vegType: 'veg', subCategory: '🥦 VEG BIRYANI' },
      { name: 'Soya Chaap Biryani', price: 280, vegType: 'veg', subCategory: '🥦 VEG BIRYANI' },
      { name: 'Eggless Special Biryani', price: 290, vegType: 'veg', subCategory: '🥦 VEG BIRYANI' },

      // 🍗 CHICKEN BIRYANI
      { name: 'Chicken Biryani', price: 310, vegType: 'non-veg', isBestseller: true, subCategory: '🍗 CHICKEN BIRYANI' },
      { name: 'Chicken Dum Biryani', price: 330, vegType: 'non-veg', isBestseller: true, subCategory: '🍗 CHICKEN BIRYANI' },
      { name: 'Chicken Fry Piece Biryani', price: 340, vegType: 'non-veg', isBestseller: true, subCategory: '🍗 CHICKEN BIRYANI' },
      { name: 'Chicken 65 Biryani', price: 350, vegType: 'non-veg', isBestseller: true, subCategory: '🍗 CHICKEN BIRYANI' },
      { name: 'Chicken Tikka Biryani', price: 350, vegType: 'non-veg', subCategory: '🍗 CHICKEN BIRYANI' },
      { name: 'Chicken Boneless Biryani', price: 360, vegType: 'non-veg', isBestseller: true, subCategory: '🍗 CHICKEN BIRYANI' },
      { name: 'Chicken Special Biryani', price: 370, vegType: 'non-veg', subCategory: '🍗 CHICKEN BIRYANI' },
      { name: 'Chicken Lollipop Biryani', price: 360, vegType: 'non-veg', subCategory: '🍗 CHICKEN BIRYANI' },
      { name: 'Chicken Keema Biryani', price: 360, vegType: 'non-veg', subCategory: '🍗 CHICKEN BIRYANI' },
      { name: 'Chicken Roast Biryani', price: 350, vegType: 'non-veg', subCategory: '🍗 CHICKEN BIRYANI' },
      { name: 'Chicken Mughlai Biryani', price: 370, vegType: 'non-veg', subCategory: '🍗 CHICKEN BIRYANI' },
      { name: 'Andhra Chicken Biryani', price: 340, vegType: 'non-veg', spicyLevel: 2, subCategory: '🍗 CHICKEN BIRYANI' },
      { name: 'Hyderabadi Chicken Biryani', price: 340, vegType: 'non-veg', isBestseller: true, spicyLevel: 2, subCategory: '🍗 CHICKEN BIRYANI' },
      { name: 'Telangana Chicken Biryani', price: 340, vegType: 'non-veg', spicyLevel: 2, subCategory: '🍗 CHICKEN BIRYANI' },
      { name: 'Rayalaseema Chicken Biryani', price: 350, vegType: 'non-veg', spicyLevel: 3, subCategory: '🍗 CHICKEN BIRYANI' },

      // 🐐 MUTTON BIRYANI
      { name: 'Mutton Biryani', price: 420, vegType: 'non-veg', isBestseller: true, subCategory: '🐐 MUTTON BIRYANI' },
      { name: 'Mutton Dum Biryani', price: 450, vegType: 'non-veg', isBestseller: true, subCategory: '🐐 MUTTON BIRYANI' },
      { name: 'Mutton Fry Piece Biryani', price: 460, vegType: 'non-veg', subCategory: '🐐 MUTTON BIRYANI' },
      { name: 'Mutton Keema Biryani', price: 460, vegType: 'non-veg', subCategory: '🐐 MUTTON BIRYANI' },
      { name: 'Mutton Special Biryani', price: 480, vegType: 'non-veg', isChefSpecial: true, subCategory: '🐐 MUTTON BIRYANI' },
      { name: 'Hyderabadi Mutton Biryani', price: 450, vegType: 'non-veg', isBestseller: true, spicyLevel: 2, subCategory: '🐐 MUTTON BIRYANI' },
      { name: 'Andhra Mutton Biryani', price: 440, vegType: 'non-veg', spicyLevel: 2, subCategory: '🐐 MUTTON BIRYANI' },
      { name: 'Telangana Mutton Biryani', price: 440, vegType: 'non-veg', spicyLevel: 2, subCategory: '🐐 MUTTON BIRYANI' },
    ],
  },
  {
    name: 'Main Course',
    order: 3,
    items: [
      // 🥦 VEG MAIN COURSE
      { name: 'Veg Biryani', price: 240, vegType: 'veg', subCategory: '🥦 VEG MAIN COURSE' },
      { name: 'Pulihora (Tamarind Rice)', price: 180, vegType: 'veg', isBestseller: true, subCategory: '🥦 VEG MAIN COURSE' },
      { name: 'Tomato Pappu with Rice', price: 190, vegType: 'veg', isBestseller: true, subCategory: '🥦 VEG MAIN COURSE' },
      { name: 'Gutti Vankaya with Rice', price: 220, vegType: 'veg', isChefSpecial: true, subCategory: '🥦 VEG MAIN COURSE' },
      { name: 'Sambar Rice', price: 170, vegType: 'veg', subCategory: '🥦 VEG MAIN COURSE' },
      { name: 'Dal Makhani Signature', price: 260, vegType: 'veg', isBestseller: true, subCategory: '🥦 VEG MAIN COURSE' },
      { name: 'Kadhai Paneer Special', price: 290, vegType: 'veg', subCategory: '🥦 VEG MAIN COURSE' },

      // 🍗 NON VEG MAIN COURSE
      { name: 'Chicken Curry', price: 290, vegType: 'non-veg', isBestseller: true, subCategory: '🍗 NON VEG MAIN COURSE' },
      { name: 'Chicken Fry', price: 300, vegType: 'non-veg', isBestseller: true, subCategory: '🍗 NON VEG MAIN COURSE' },
      { name: 'Mutton Curry', price: 420, vegType: 'non-veg', isBestseller: true, spicyLevel: 2, subCategory: '🍗 NON VEG MAIN COURSE' },
      { name: 'Fish Pulusu', price: 350, vegType: 'non-veg', isBestseller: true, spicyLevel: 2, subCategory: '🍗 NON VEG MAIN COURSE' },
      { name: 'Egg Curry', price: 210, vegType: 'egg', subCategory: '🍗 NON VEG MAIN COURSE' },
      { name: 'Butter Chicken Grand Style', price: 360, vegType: 'non-veg', isBestseller: true, subCategory: '🍗 NON VEG MAIN COURSE' },
    ],
  },
  {
    name: 'Breads',
    order: 4,
    items: [
      { name: 'Butter Garlic Naan', price: 70, vegType: 'veg', isBestseller: true },
      { name: 'Cheese Chilli Naan', price: 90, vegType: 'veg' },
      { name: 'Lachha Paratha', price: 60, vegType: 'veg' },
    ],
  },
  {
    name: 'Desserts',
    order: 5,
    items: [
      { name: 'Gulab Jamun with Rabri', price: 160, vegType: 'veg', isBestseller: true },
      { name: 'Saffron Rasmalai', price: 180, vegType: 'veg' },
    ],
  },
  {
    name: 'Drinks',
    order: 6,
    items: [
      { name: 'Mango Lassi Delight', price: 130, vegType: 'veg', isBestseller: true },
    ],
  },
];

module.exports = { defaultCategories };
