const defaultCategories = [
  {
    name: 'Starters',
    order: 1,
    items: [
      // 🥗 VEG STARTERS
      {
        name: 'Gobi 65',
        price: 190,
        vegType: 'veg',
        subCategory: '🥗 VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030230/flashmenu/defaults/pseykx1pl4d7yljdelei.webp',
      },
      {
        name: 'Gobi Manchurian',
        price: 190,
        vegType: 'veg',
        subCategory: '🥗 VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030230/flashmenu/defaults/pseykx1pl4d7yljdelei.webp',
      },
      {
        name: 'Chilli Gobi',
        price: 190,
        vegType: 'veg',
        subCategory: '🥗 VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030230/flashmenu/defaults/pseykx1pl4d7yljdelei.webp',
      },
      {
        name: 'Paneer 65',
        price: 240,
        vegType: 'veg',
        subCategory: '🥗 VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030020/flashmenu/defaults/jthgdhnlhe2kcwxxrtlg.jpg',
      },
      {
        name: 'Chilli Paneer',
        price: 240,
        vegType: 'veg',
        isBestseller: true,
        subCategory: '🥗 VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030020/flashmenu/defaults/jthgdhnlhe2kcwxxrtlg.jpg',
      },
      {
        name: 'Paneer Manchurian',
        price: 240,
        vegType: 'veg',
        subCategory: '🥗 VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030020/flashmenu/defaults/jthgdhnlhe2kcwxxrtlg.jpg',
      },
      {
        name: 'Paneer Majestic',
        price: 260,
        vegType: 'veg',
        isBestseller: true,
        subCategory: '🥗 VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030020/flashmenu/defaults/jthgdhnlhe2kcwxxrtlg.jpg',
      },
      {
        name: 'Paneer Tikka',
        price: 260,
        vegType: 'veg',
        subCategory: '🥗 VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030020/flashmenu/defaults/jthgdhnlhe2kcwxxrtlg.jpg',
      },
      {
        name: 'Crispy Corn',
        price: 210,
        vegType: 'veg',
        isBestseller: true,
        subCategory: '🥗 VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030405/flashmenu/defaults/jmtug7nka8djwopq2bxj.jpg',
      },
      {
        name: 'Corn Fry',
        price: 190,
        vegType: 'veg',
        subCategory: '🥗 VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030405/flashmenu/defaults/jmtug7nka8djwopq2bxj.jpg',
      },
      {
        name: 'Baby Corn 65',
        price: 210,
        vegType: 'veg',
        subCategory: '🥗 VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030405/flashmenu/defaults/jmtug7nka8djwopq2bxj.jpg',
      },
      {
        name: 'Baby Corn Manchurian',
        price: 210,
        vegType: 'veg',
        subCategory: '🥗 VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030405/flashmenu/defaults/jmtug7nka8djwopq2bxj.jpg',
      },
      {
        name: 'Chilli Baby Corn',
        price: 210,
        vegType: 'veg',
        subCategory: '🥗 VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030405/flashmenu/defaults/jmtug7nka8djwopq2bxj.jpg',
      },
      {
        name: 'Crispy Baby Corn',
        price: 220,
        vegType: 'veg',
        subCategory: '🥗 VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030405/flashmenu/defaults/jmtug7nka8djwopq2bxj.jpg',
      },
      {
        name: 'Mushroom 65',
        price: 230,
        vegType: 'veg',
        subCategory: '🥗 VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030540/flashmenu/defaults/tbtqhnld9hwtmg6hi0xp.jpg',
      },
      {
        name: 'Mushroom Manchurian',
        price: 230,
        vegType: 'veg',
        subCategory: '🥗 VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030540/flashmenu/defaults/tbtqhnld9hwtmg6hi0xp.jpg',
      },
      {
        name: 'Chilli Mushroom',
        price: 230,
        vegType: 'veg',
        subCategory: '🥗 VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030540/flashmenu/defaults/tbtqhnld9hwtmg6hi0xp.jpg',
      },
      {
        name: 'Pepper Mushroom',
        price: 240,
        vegType: 'veg',
        subCategory: '🥗 VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030540/flashmenu/defaults/tbtqhnld9hwtmg6hi0xp.jpg',
      },
      {
        name: 'Mushroom Fry',
        price: 230,
        vegType: 'veg',
        subCategory: '🥗 VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030540/flashmenu/defaults/tbtqhnld9hwtmg6hi0xp.jpg',
      },
      
      
      
      
      
      
      


      // 🍗 NON VEG STARTERS
      {
        name: 'Chicken 65',
        price: 280,
        vegType: 'non-veg',
        isBestseller: true,
        subCategory: '🍗 NON VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Chilli Chicken',
        price: 280,
        vegType: 'non-veg',
        isBestseller: true,
        subCategory: '🍗 NON VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Chicken Manchurian',
        price: 280,
        vegType: 'non-veg',
        subCategory: '🍗 NON VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Chicken Majestic',
        price: 290,
        vegType: 'non-veg',
        isBestseller: true,
        subCategory: '🍗 NON VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Chicken 555',
        price: 290,
        vegType: 'non-veg',
        subCategory: '🍗 NON VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Chicken 999',
        price: 290,
        vegType: 'non-veg',
        subCategory: '🍗 NON VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Chicken Lollipop',
        price: 310,
        vegType: 'non-veg',
        isBestseller: true,
        subCategory: '🍗 NON VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787031374/flashmenu/defaults/h9opsrirvsiayqnw8x3j.jpg',
      },
      {
        name: 'Chicken Drumsticks',
        price: 310,
        vegType: 'non-veg',
        subCategory: '🍗 NON VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Chicken Wings',
        price: 290,
        vegType: 'non-veg',
        subCategory: '🍗 NON VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787031768/flashmenu/defaults/gpis9spkpc2ic3oo53w7.jpg',
      },
      {
        name: 'Chicken Pakoda',
        price: 260,
        vegType: 'non-veg',
        subCategory: '🍗 NON VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Chicken Fry',
        price: 270,
        vegType: 'non-veg',
        subCategory: '🍗 NON VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Kodi Vepudu',
        price: 310,
        vegType: 'non-veg',
        isBestseller: true,
        subCategory: '🍗 NON VEG STARTERS',
        image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Kodi Miriyala Vepudu',
        price: 320,
        vegType: 'non-veg',
        spicyLevel: 2,
        subCategory: '🍗 NON VEG STARTERS',
        image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Guntur Chilli Chicken',
        price: 290,
        vegType: 'non-veg',
        spicyLevel: 3,
        subCategory: '🍗 NON VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Pepper Chicken',
        price: 290,
        vegType: 'non-veg',
        spicyLevel: 2,
        subCategory: '🍗 NON VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Ginger Chicken',
        price: 280,
        vegType: 'non-veg',
        subCategory: '🍗 NON VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Garlic Chicken',
        price: 280,
        vegType: 'non-veg',
        subCategory: '🍗 NON VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Lemon Chicken',
        price: 280,
        vegType: 'non-veg',
        subCategory: '🍗 NON VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Dragon Chicken',
        price: 310,
        vegType: 'non-veg',
        spicyLevel: 2,
        subCategory: '🍗 NON VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Schezwan Chicken',
        price: 290,
        vegType: 'non-veg',
        spicyLevel: 2,
        subCategory: '🍗 NON VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787032015/flashmenu/defaults/kywje66fthiytdfemfyu.png',
      },
      {
        name: 'Crispy Chicken',
        price: 290,
        vegType: 'non-veg',
        subCategory: '🍗 NON VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Chicken Roast',
        price: 320,
        vegType: 'non-veg',
        subCategory: '🍗 NON VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Rayalaseema Chicken Fry',
        price: 320,
        vegType: 'non-veg',
        spicyLevel: 3,
        subCategory: '🍗 NON VEG STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      
      
      

      // 🔥 TANDOORI / KEBAB STARTERS
      {
        name: 'Tandoori Chicken',
        price: 360,
        vegType: 'non-veg',
        isBestseller: true,
        subCategory: '🔥 TANDOORI / KEBAB STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Chicken Tikka',
        price: 320,
        vegType: 'non-veg',
        isBestseller: true,
        subCategory: '🔥 TANDOORI / KEBAB STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Chicken Malai Tikka',
        price: 340,
        vegType: 'non-veg',
        subCategory: '🔥 TANDOORI / KEBAB STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Chicken Tangdi Kebab',
        price: 340,
        vegType: 'non-veg',
        subCategory: '🔥 TANDOORI / KEBAB STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Chicken Seekh Kebab',
        price: 330,
        vegType: 'non-veg',
        subCategory: '🔥 TANDOORI / KEBAB STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Chicken Reshmi Kebab',
        price: 340,
        vegType: 'non-veg',
        subCategory: '🔥 TANDOORI / KEBAB STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Chicken Hariyali Kebab',
        price: 330,
        vegType: 'non-veg',
        subCategory: '🔥 TANDOORI / KEBAB STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Chicken Achari Kebab',
        price: 330,
        vegType: 'non-veg',
        subCategory: '🔥 TANDOORI / KEBAB STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Chicken Garlic Kebab',
        price: 330,
        vegType: 'non-veg',
        subCategory: '🔥 TANDOORI / KEBAB STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030876/flashmenu/defaults/ygzh7fryr3aezp6elbli.webp',
      },
      {
        name: 'Murgh Malai Kebab',
        price: 350,
        vegType: 'non-veg',
        subCategory: '🔥 TANDOORI / KEBAB STARTERS',
        image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Paneer Tikka',
        price: 270,
        vegType: 'veg',
        subCategory: '🔥 TANDOORI / KEBAB STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030020/flashmenu/defaults/jthgdhnlhe2kcwxxrtlg.jpg',
      },
      {
        name: 'Paneer Malai Tikka',
        price: 280,
        vegType: 'veg',
        subCategory: '🔥 TANDOORI / KEBAB STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030020/flashmenu/defaults/jthgdhnlhe2kcwxxrtlg.jpg',
      },
      {
        name: 'Paneer Achari Tikka',
        price: 270,
        vegType: 'veg',
        subCategory: '🔥 TANDOORI / KEBAB STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030020/flashmenu/defaults/jthgdhnlhe2kcwxxrtlg.jpg',
      },
      {
        name: 'Paneer Hariyali Tikka',
        price: 270,
        vegType: 'veg',
        subCategory: '🔥 TANDOORI / KEBAB STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030020/flashmenu/defaults/jthgdhnlhe2kcwxxrtlg.jpg',
      },
      
      

      // 🐟 FISH STARTERS
      {
        name: 'Apollo Fish',
        price: 340,
        vegType: 'non-veg',
        isBestseller: true,
        subCategory: '🐟 FISH STARTERS',
        image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Fish 65',
        price: 330,
        vegType: 'non-veg',
        subCategory: '🐟 FISH STARTERS',
        image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Fish Fry',
        price: 330,
        vegType: 'non-veg',
        isBestseller: true,
        subCategory: '🐟 FISH STARTERS',
        image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Andhra Fish Fry',
        price: 340,
        vegType: 'non-veg',
        spicyLevel: 2,
        subCategory: '🐟 FISH STARTERS',
        image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Chepa Vepudu',
        price: 350,
        vegType: 'non-veg',
        isBestseller: true,
        spicyLevel: 2,
        subCategory: '🐟 FISH STARTERS',
        image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Chilli Fish',
        price: 330,
        vegType: 'non-veg',
        subCategory: '🐟 FISH STARTERS',
        image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Fish Manchurian',
        price: 330,
        vegType: 'non-veg',
        subCategory: '🐟 FISH STARTERS',
        image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Ginger Fish',
        price: 330,
        vegType: 'non-veg',
        subCategory: '🐟 FISH STARTERS',
        image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Pepper Fish',
        price: 340,
        vegType: 'non-veg',
        spicyLevel: 2,
        subCategory: '🐟 FISH STARTERS',
        image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Schezwan Fish',
        price: 340,
        vegType: 'non-veg',
        spicyLevel: 2,
        subCategory: '🐟 FISH STARTERS',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787032015/flashmenu/defaults/kywje66fthiytdfemfyu.png',
      },
      {
        name: 'Fish Fingers',
        price: 320,
        vegType: 'non-veg',
        subCategory: '🐟 FISH STARTERS',
        image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Fish Tikka',
        price: 350,
        vegType: 'non-veg',
        subCategory: '🐟 FISH STARTERS',
        image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Fish Roast',
        price: 350,
        vegType: 'non-veg',
        subCategory: '🐟 FISH STARTERS',
        image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Salt & Pepper Fish',
        price: 340,
        vegType: 'non-veg',
        subCategory: '🐟 FISH STARTERS',
        image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
      },

      // 🦐 PRAWN STARTERS
      {
        name: 'Prawns 65',
        price: 360,
        vegType: 'non-veg',
        subCategory: '🦐 PRAWN STARTERS',
        image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Prawns Fry',
        price: 370,
        vegType: 'non-veg',
        isBestseller: true,
        subCategory: '🦐 PRAWN STARTERS',
        image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Royyala Vepudu',
        price: 380,
        vegType: 'non-veg',
        isBestseller: true,
        spicyLevel: 2,
        subCategory: '🦐 PRAWN STARTERS',
        image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Chilli Prawns',
        price: 360,
        vegType: 'non-veg',
        subCategory: '🦐 PRAWN STARTERS',
        image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Loose Prawns',
        price: 380,
        vegType: 'non-veg',
        isBestseller: true,
        subCategory: '🦐 PRAWN STARTERS',
        image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Pepper Prawns',
        price: 370,
        vegType: 'non-veg',
        spicyLevel: 2,
        subCategory: '🦐 PRAWN STARTERS',
        image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Garlic Prawns',
        price: 360,
        vegType: 'non-veg',
        subCategory: '🦐 PRAWN STARTERS',
        image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Butter Garlic Prawns',
        price: 390,
        vegType: 'non-veg',
        isChefSpecial: true,
        subCategory: '🦐 PRAWN STARTERS',
        image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Golden Fried Prawns',
        price: 380,
        vegType: 'non-veg',
        subCategory: '🦐 PRAWN STARTERS',
        image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Achari Prawns',
        price: 370,
        vegType: 'non-veg',
        subCategory: '🦐 PRAWN STARTERS',
        image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Hariyali Prawns',
        price: 370,
        vegType: 'non-veg',
        subCategory: '🦐 PRAWN STARTERS',
        image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=600&q=80',
      },
    ],
  },
  {
    name: 'Biryanis',
    order: 2,
    items: [
      // 🥦 VEG BIRYANI
      {
        name: 'Veg Biryani',
        price: 240,
        vegType: 'veg',
        subCategory: '🥦 VEG BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787033516/flashmenu/defaults/zgd53yinghfapcab8kix.avif',
      },
      {
        name: 'Vegetable Dum Biryani',
        price: 260,
        vegType: 'veg',
        subCategory: '🥦 VEG BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787033516/flashmenu/defaults/zgd53yinghfapcab8kix.avif',
      },
      {
        name: 'Veg Dum Biryani',
        price: 260,
        vegType: 'veg',
        subCategory: '🥦 VEG BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787033516/flashmenu/defaults/zgd53yinghfapcab8kix.avif',
      },
      {
        name: 'Paneer Biryani',
        price: 290,
        vegType: 'veg',
        isBestseller: true,
        subCategory: '🥦 VEG BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787033233/flashmenu/defaults/ufsm8weanmqtjawtssi2.jpg',
      },
      {
        name: 'Paneer Tikka Biryani',
        price: 310,
        vegType: 'veg',
        subCategory: '🥦 VEG BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787033233/flashmenu/defaults/ufsm8weanmqtjawtssi2.jpg',
      },
      
      
      
      {
        name: 'Kaju Biryani',
        price: 320,
        vegType: 'veg',
        isBestseller: true,
        subCategory: '🥦 VEG BIRYANI',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Kaju Paneer Biryani',
        price: 340,
        vegType: 'veg',
        subCategory: '🥦 VEG BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787033233/flashmenu/defaults/ufsm8weanmqtjawtssi2.jpg',
      },
      
      {
        name: 'Mix Veg Biryani',
        price: 270,
        vegType: 'veg',
        subCategory: '🥦 VEG BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787033516/flashmenu/defaults/zgd53yinghfapcab8kix.avif',
      },
      
      
      

      // 🍗 CHICKEN BIRYANI
      {
        name: 'Chicken Biryani',
        price: 310,
        vegType: 'non-veg',
        isBestseller: true,
        subCategory: '🍗 CHICKEN BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787032798/flashmenu/defaults/j4zdxqifus7fmjra8smv.avif',
      },
      {
        name: 'Chicken Dum Biryani',
        price: 330,
        vegType: 'non-veg',
        isBestseller: true,
        subCategory: '🍗 CHICKEN BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787032798/flashmenu/defaults/j4zdxqifus7fmjra8smv.avif',
      },
      {
        name: 'Chicken Fry Piece Biryani',
        price: 340,
        vegType: 'non-veg',
        isBestseller: true,
        subCategory: '🍗 CHICKEN BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787032798/flashmenu/defaults/j4zdxqifus7fmjra8smv.avif',
      },
      {
        name: 'Chicken 65 Biryani',
        price: 350,
        vegType: 'non-veg',
        isBestseller: true,
        subCategory: '🍗 CHICKEN BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787032798/flashmenu/defaults/j4zdxqifus7fmjra8smv.avif',
      },
      {
        name: 'Chicken Tikka Biryani',
        price: 350,
        vegType: 'non-veg',
        subCategory: '🍗 CHICKEN BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787032798/flashmenu/defaults/j4zdxqifus7fmjra8smv.avif',
      },
      {
        name: 'Chicken Boneless Biryani',
        price: 360,
        vegType: 'non-veg',
        isBestseller: true,
        subCategory: '🍗 CHICKEN BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787032798/flashmenu/defaults/j4zdxqifus7fmjra8smv.avif',
      },
      {
        name: 'Chicken Special Biryani',
        price: 370,
        vegType: 'non-veg',
        subCategory: '🍗 CHICKEN BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787032798/flashmenu/defaults/j4zdxqifus7fmjra8smv.avif',
      },
      {
        name: 'Chicken Lollipop Biryani',
        price: 360,
        vegType: 'non-veg',
        subCategory: '🍗 CHICKEN BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787032798/flashmenu/defaults/j4zdxqifus7fmjra8smv.avif',
      },
      {
        name: 'Chicken Keema Biryani',
        price: 360,
        vegType: 'non-veg',
        subCategory: '🍗 CHICKEN BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787032798/flashmenu/defaults/j4zdxqifus7fmjra8smv.avif',
      },
      {
        name: 'Chicken Roast Biryani',
        price: 350,
        vegType: 'non-veg',
        subCategory: '🍗 CHICKEN BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787032798/flashmenu/defaults/j4zdxqifus7fmjra8smv.avif',
      },
      {
        name: 'Chicken Mughlai Biryani',
        price: 370,
        vegType: 'non-veg',
        subCategory: '🍗 CHICKEN BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787032798/flashmenu/defaults/j4zdxqifus7fmjra8smv.avif',
      },
      {
        name: 'Andhra Chicken Biryani',
        price: 340,
        vegType: 'non-veg',
        spicyLevel: 2,
        subCategory: '🍗 CHICKEN BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787032798/flashmenu/defaults/j4zdxqifus7fmjra8smv.avif',
      },
      {
        name: 'Hyderabadi Chicken Biryani',
        price: 340,
        vegType: 'non-veg',
        isBestseller: true,
        spicyLevel: 2,
        subCategory: '🍗 CHICKEN BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787032798/flashmenu/defaults/j4zdxqifus7fmjra8smv.avif',
      },
      {
        name: 'Telangana Chicken Biryani',
        price: 340,
        vegType: 'non-veg',
        spicyLevel: 2,
        subCategory: '🍗 CHICKEN BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787032798/flashmenu/defaults/j4zdxqifus7fmjra8smv.avif',
      },
      {
        name: 'Rayalaseema Chicken Biryani',
        price: 350,
        vegType: 'non-veg',
        spicyLevel: 3,
        subCategory: '🍗 CHICKEN BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787032798/flashmenu/defaults/j4zdxqifus7fmjra8smv.avif',
      },

      // 🐐 MUTTON BIRYANI
      {
        name: 'Mutton Biryani',
        price: 420,
        vegType: 'non-veg',
        isBestseller: true,
        subCategory: '🐐 MUTTON BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787033742/flashmenu/defaults/hkbrheqvayzee5maj41i.jpg',
      },
      {
        name: 'Mutton Dum Biryani',
        price: 450,
        vegType: 'non-veg',
        isBestseller: true,
        subCategory: '🐐 MUTTON BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787033742/flashmenu/defaults/hkbrheqvayzee5maj41i.jpg',
      },
      {
        name: 'Mutton Fry Piece Biryani',
        price: 460,
        vegType: 'non-veg',
        subCategory: '🐐 MUTTON BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787033742/flashmenu/defaults/hkbrheqvayzee5maj41i.jpg',
      },
      {
        name: 'Mutton Keema Biryani',
        price: 460,
        vegType: 'non-veg',
        subCategory: '🐐 MUTTON BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787033742/flashmenu/defaults/hkbrheqvayzee5maj41i.jpg',
      },
      {
        name: 'Mutton Special Biryani',
        price: 480,
        vegType: 'non-veg',
        isChefSpecial: true,
        subCategory: '🐐 MUTTON BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787033742/flashmenu/defaults/hkbrheqvayzee5maj41i.jpg',
      },
      {
        name: 'Hyderabadi Mutton Biryani',
        price: 450,
        vegType: 'non-veg',
        isBestseller: true,
        spicyLevel: 2,
        subCategory: '🐐 MUTTON BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787033742/flashmenu/defaults/hkbrheqvayzee5maj41i.jpg',
      },
      {
        name: 'Andhra Mutton Biryani',
        price: 440,
        vegType: 'non-veg',
        spicyLevel: 2,
        subCategory: '🐐 MUTTON BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787033742/flashmenu/defaults/hkbrheqvayzee5maj41i.jpg',
      },
      {
        name: 'Telangana Mutton Biryani',
        price: 440,
        vegType: 'non-veg',
        spicyLevel: 2,
        subCategory: '🐐 MUTTON BIRYANI',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787033742/flashmenu/defaults/hkbrheqvayzee5maj41i.jpg',
      },
    ],
  },
  {
    name: 'Main Course',
    order: 3,
    items: [
      // 🥦 VEG MAIN COURSE
      {
        name: 'Pulihora (Tamarind Rice)',
        price: 180,
        vegType: 'veg',
        isBestseller: true,
        subCategory: '🥦 VEG MAIN COURSE',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787034158/flashmenu/defaults/fw4cy34ngenpszz908kt.webp',
      },
      {
        name: 'Tomato Pappu with Rice',
        price: 190,
        vegType: 'veg',
        isBestseller: true,
        subCategory: '🥦 VEG MAIN COURSE',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Gutti Vankaya with Rice',
        price: 220,
        vegType: 'veg',
        isChefSpecial: true,
        subCategory: '🥦 VEG MAIN COURSE',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Sambar Rice',
        price: 170,
        vegType: 'veg',
        subCategory: '🥦 VEG MAIN COURSE',
        image: 'https://images.unsplash.com/photo-1516714435131-44d6b64dc6a2?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Dal Makhani Signature',
        price: 260,
        vegType: 'veg',
        isBestseller: true,
        subCategory: '🥦 VEG MAIN COURSE',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Kadhai Paneer Special',
        price: 290,
        vegType: 'veg',
        subCategory: '🥦 VEG MAIN COURSE',
        image: 'https://res.cloudinary.com/xt6ci0uh/image/upload/v1787030020/flashmenu/defaults/jthgdhnlhe2kcwxxrtlg.jpg',
      },

      // 🍗 NON VEG MAIN COURSE
      {
        name: 'Chicken Curry',
        price: 290,
        vegType: 'non-veg',
        isBestseller: true,
        subCategory: '🍗 NON VEG MAIN COURSE',
        image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Chicken Fry',
        price: 300,
        vegType: 'non-veg',
        isBestseller: true,
        subCategory: '🍗 NON VEG MAIN COURSE',
        image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Mutton Curry',
        price: 420,
        vegType: 'non-veg',
        isBestseller: true,
        spicyLevel: 2,
        subCategory: '🍗 NON VEG MAIN COURSE',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Fish Pulusu',
        price: 350,
        vegType: 'non-veg',
        isBestseller: true,
        spicyLevel: 2,
        subCategory: '🍗 NON VEG MAIN COURSE',
        image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Egg Curry',
        price: 210,
        vegType: 'egg',
        subCategory: '🍗 NON VEG MAIN COURSE',
        image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Butter Chicken Grand Style',
        price: 360,
        vegType: 'non-veg',
        isBestseller: true,
        subCategory: '🍗 NON VEG MAIN COURSE',
        image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=600&q=80',
      },
    ],
  },
  {
    name: 'Breads',
    order: 4,
    items: [
      {
        name: 'Butter Garlic Naan',
        price: 70,
        vegType: 'veg',
        isBestseller: true,
        image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Cheese Chilli Naan',
        price: 90,
        vegType: 'veg',
        image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Lachha Paratha',
        price: 60,
        vegType: 'veg',
        image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80',
      },
    ],
  },
  {
    name: 'Desserts',
    order: 5,
    items: [
      {
        name: 'Gulab Jamun with Rabri',
        price: 160,
        vegType: 'veg',
        isBestseller: true,
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Saffron Rasmalai',
        price: 180,
        vegType: 'veg',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
      },
    ],
  },
  {
    name: 'Drinks',
    order: 6,
    items: [
      {
        name: 'Mango Lassi Delight',
        price: 130,
        vegType: 'veg',
        isBestseller: true,
        image: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Sprite',
        price: 50,
        vegType: 'veg',
        image: 'https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Thums Up',
        price: 50,
        vegType: 'veg',
        isBestseller: true,
        image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Coca-Cola',
        price: 50,
        vegType: 'veg',
        image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80',
      },
    ],
  },
];

module.exports = { defaultCategories };
